import os

WINDOWN_WIDTH = 500
WINDOWN_HEIGHT= 250
WINDOWN_POSITION_RIGHT = 300
WINDOWN_POSITION_DOWN = 100

COLOR_GREEN = '#00FF00'
COLOR_RED = '#FF0000'

PATH_DIRECTORY = os.path.dirname(__file__)
PATH_IMAGE = os.path.join(PATH_DIRECTORY, 'images')